[package]
name = "cli-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4"
image = "0.23"
imageproc ="0.22"
rusttype = "0.9"
lazy_static = "1.4"
chrono = "0.4"
