name: Build ProjectCDC

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build
        run: msbuild ProjectCDC/MasterTool/UsbScreen.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MasterToolCDC
          path: ProjectCDC/MasterTool/UsbScreen/bin/Release
